#!/bin/bash
if [ $# -ne 2 ]; then 
	echo "Incorrect number of parameters" >&2
	exit 1
fi

if [ ! -x "$2" ]; then
	echo "$2 Is not executable." >&2
	exit 1
fi

for test in $(cat "$1") 
do
	if [ -e $test".in" ]; then
		if [ -e $test".args" ]; then 
			"$2" $(cat $test".args") < $test".in" > $test".out"
		else 
			"$2" < $test".in" > $test".out"
		fi
	elif [ -e $test".args" ]; then
		"$2" $(cat $test".args") > $test".out"
	else
		"$2" > $test".out"
	fi
done
exit
